#ifndef __HARDWARE_DEFINTIONS_HPP__
#define __HARDWARE_DEFINTIONS_HPP__

#define STEPPER_STEP 17
#define STEPPER_DIR 27

#define STEPPER_MS1 10
#define STEPPER_MS2 9
#define STEPPER_MS3 11

// SPM -> Steps/Minute
#define STEPPER_MAX_SPM 4000
#define STEPPER_SPM_UPPER 1000

#endif